@startuml Administrator
left to right direction

actor "Administrator" as Admin

usecase "PU041:\nWyświetlenie\nlogów systemu" as PU041
usecase "PU042:\nWyświetlenie listy\nużytkowników" as PU042
usecase "PU043:\nNadanie uprawnień\nużytkownikowi" as PU043
usecase "PU044:\nDodanie konta\nużytkownika" as PU044
usecase "PU045:\nEdytowanie konta\nużytkownika" as PU045
usecase "PU046:\nUsunięcie konta\nużytkownika" as PU046
usecase "PU047:\nZmienienie parametrów\nsystemu" as PU047

Admin --> PU041
Admin --> PU042
Admin --> PU047

PU042 ..> PU043 : <<invoke>>
PU042 ..> PU044 : <<invoke>>
PU042 ..> PU045 : <<invoke>>
PU042 ..> PU046 : <<invoke>>

@enduml