@startuml Czas
left to right direction

actor "Czas" as Time

usecase "PU029: Wysłanie powiadomienia\no zmianach w zbiorze danych\nsubskrybentom" as PU029
usecase "PU030: Wygenerowanie raportów\nczęstotliwości pobrań\nzbiorów danych" as PU030
usecase "PU031: Stworzenie backup'u" as PU031

Time --> PU029
Time --> PU030
Time --> PU031

@enduml