@startuml Weryfikator
left to right direction

actor "Weryfikator" as Verifier

usecase "PU021: Ocena jakości danych" as UC1
usecase "PU022: Obsługa zgłoszeń" as UC2
usecase "PU023: Zatwierdzenie zmian w\n zbiorach danych" as UC3
usecase "PU024: Wygenerowanie raportu\n jakości danych" as UC4

Verifier --> UC1
Verifier --> UC2
Verifier --> UC3
Verifier --> UC4

@enduml