name: Generate dokumentacja.pdf from dokumentacja.md

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - name: Check out repository
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python  -m pip install --upgrade pip
        pip install -r automation/requirements.txt

    - name: Run script
      run: |
        source venv/bin/activate
        python automation/automation.py

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: dokumentacja.pdf
        path: dokumentacja.pdf      